apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vite-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-vite
  template:
    metadata:
      labels:
        app: react-vite
    spec:
      containers:
      - name: react-vite
        image: sanjai4334/react-vite-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-vite-service
spec:
  type: NodePort
  selector:
    app: react-vite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
